In [1]:
import numpy as np
import pandas as pd
import pickle
import datetime

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.externals import joblib

In [2]:
# Read in model object
with open('gb00.pkl', 'rb') as file:  
    model = pickle.load(file)

In [81]:
# Read in date file
dates = pd.read_csv('Dates.csv')
input_month = 'July'
display = dates[dates['MonthName'] == input_month]

In [53]:
# Identify date differences
display.loc[:,'Date'] = pd.to_datetime(display.loc[:, 'Date']).dt.date
display.loc[:,'DaysBetween'] = display.loc[:, 'Date'] - datetime.date.today()
display.loc[:,'DaysBetween'] = display.loc[:, 'DaysBetween'].dt.days

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexing.py:362: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)

In [54]:
# Add other variables
display.loc[:, 'Gender'] = 1
display.loc[:, 'Age'] = 24
display.loc[:, 'Scholarship'] = 0
display.loc[:, 'Hipertension'] = 0
display.loc[:, 'Diabetes'] = 0
display.loc[:, 'PreviousMiss'] = 0
display.loc[:, 'Alcoholism'] = 0
display.loc[:, 'Handcap'] = 0
display.loc[:, 'SMS_received'] = 0

In [55]:
pred_data = display.drop(
    [
        'MonthName', 'Month', 'Year', 'Day', 'Date', 'Weekday', 'DayOfWeek', 
        'DayLabel', 'WeekOfMonth',
    ],
    axis = 1
)

In [56]:
pred_data.columns

Index(['DaysBetween', 'Gender', 'Age', 'Scholarship', 'Hipertension',
       'Diabetes', 'PreviousMiss', 'Alcoholism', 'Handcap', 'SMS_received'],
      dtype='object')

In [78]:

probs = model.predict_proba(pred_data)
probs = pd.Series([i[1] for i in probs])

In [88]:
display['Prob'] = probs

In [89]:
display['Prob']

0     0.000339
1     0.000339
2     0.000339
3     0.000339
4     0.000339
5     0.000339
6     0.000339
7     0.000339
8     0.000339
9     0.000339
10    0.000339
11    0.000339
12    0.000339
13    0.000339
14    0.000339
15    0.000339
16    0.000339
17    0.000339
18    0.000339
19    0.000339
20    0.000339
21    0.000339
22    0.000339
23    0.000339
24    0.000339
25    0.000339
26    0.000339
27    0.000339
28    0.000339
29    0.000339
30    0.000339
Name: Prob, dtype: float64

In [87]:
display = display.reset_index()

In [91]:
display = display.drop('index')

KeyError: "['index'] not found in axis"

In [33]:
probs = model.predict_proba(pred_data)

In [35]:
probs_series = pd.Series(i[1] for i in probs)

In [36]:
probs_series

0     0.000339
1     0.000339
2     0.000339
3     0.000339
4     0.000339
5     0.000339
6     0.000339
7     0.000339
8     0.000339
9     0.000339
10    0.000339
11    0.000339
12    0.000339
13    0.000339
14    0.000339
15    0.000339
16    0.000339
17    0.000339
18    0.000339
19    0.000339
20    0.000339
21    0.000339
22    0.000339
23    0.000339
24    0.000339
25    0.000339
26    0.000339
27    0.000339
28    0.000339
29    0.000339
30    0.000339
dtype: float64

In [30]:
display

,MonthName,Month,Year,Day,Date,Weekday,DayOfWeek,DayLabel,WeekOfMonth,DaysBetween,Gender,Age,Scholarship,Hipertension,Diabetes,PreviousMiss,Alcoholism,Handcap,SMS_received,Prob
61,August,8,2019,1,2019-08-01,Thursday,5,Th,1,45,1,24,0,0,0,0,0,0,0,NaN
62,August,8,2019,2,2019-08-02,Friday,6,Fr,1,46,1,24,0,0,0,0,0,0,0,NaN
63,August,8,2019,3,2019-08-03,Saturday,7,Sa,1,47,1,24,0,0,0,0,0,0,0,NaN
64,August,8,2019,4,2019-08-04,Sunday,1,Su,2,48,1,24,0,0,0,0,0,0,0,NaN
65,August,8,2019,5,2019-08-05,Monday,2,Mo,2,49,1,24,0,0,0,0,0,0,0,NaN
66,August,8,2019,6,2019-08-06,Tuesday,3,Tu,2,50,1,24,0,0,0,0,0,0,0,NaN
67,August,8,2019,7,2019-08-07,Wednesday,4,We,2,51,1,24,0,0,0,0,0,0,0,NaN
68,August,8,2019,8,2019-08-08,Thursday,5,Th,2,52,1,24,0,0,0,0,0,0,0,NaN
69,August,8,2019,9,2019-08-09,Friday,6,Fr,2,53,1,24,0,0,0,0,0,0,0,NaN
70,August,8,2019,10,2019-08-10,Saturday,7,Sa,2,54,1,24,0,0,0,0,0,0,0,NaN
71,August,8,2019,11,2019-08-11,Sunday,1,Su,3,55,1,24,0,0,0,0,0,0,0,NaN
72,August,8,2019,12,2019-08-12,Monday,2,Mo,3,56,1,24,0,0,0,0,0,0,0,NaN
73,August,8,2019,13,2019-08-13,Tuesday,3,Tu,3,57,1,24,0,0,0,0,0,0,0,NaN
74,August,8,2019,14,2019-08-14,Wednesday,4,We,3,58,1,24,0,0,0,0,0,0,0,NaN
75,August,8,2019,15,2019-08-15,Thursday,5,Th,3,59,1,24,0,0,0,0,0,0,0,NaN
76,August,8,2019,16,2019-08-16,Friday,6,Fr,3,60,1,24,0,0,0,0,0,0,0,NaN
77,August,8,2019,17,2019-08-17,Saturday,7,Sa,3,61,1,24,0,0,0,0,0,0,0,NaN
78,August,8,2019,18,2019-08-18,Sunday,1,Su,4,62,1,24,0,0,0,0,0,0,0,NaN
79,August,8,2019,19,2019-08-19,Monday,2,Mo,4,63,1,24,0,0,0,0,0,0,0,NaN
80,August,8,2019,20,2019-08-20,Tuesday,3,Tu,4,64,1,24,0,0,0,0,0,0,0,NaN
81,August,8,2019,21,2019-08-21,Wednesday,4,We,4,65,1,24,0,0,0,0,0,0,0,NaN
82,August,8,2019,22,2019-08-22,Thursday,5,Th,4,66,1,24,0,0,0,0,0,0,0,NaN
83,August,8,2019,23,2019-08-23,Friday,6,Fr,4,67,1,24,0,0,0,0,0,0,0,NaN
84,August,8,2019,24,2019-08-24,Saturday,7,Sa,4,68,1,24,0,0,0,0,0,0,0,NaN
85,August,8,2019,25,2019-08-25,Sunday,1,Su,5,69,1,24,0,0,0,0,0,0,0,NaN
86,August,8,2019,26,2019-08-26,Monday,2,Mo,5,70,1,24,0,0,0,0,0,0,0,NaN
87,August,8,2019,27,2019-08-27,Tuesday,3,Tu,5,71,1,24,0,0,0,0,0,0,0,NaN
88,August,8,2019,28,2019-08-28,Wednesday,4,We,5,72,1,24,0,0,0,0,0,0,0,NaN
89,August,8,2019,29,2019-08-29,Thursday,5,Th,5,73,1,24,0,0,0,0,0,0,0,NaN
90,August,8,2019,30,2019-08-30,Friday,6,Fr,5,74,1,24,0,0,0,0,0,0,0,NaN
91,August,8,2019,31,2019-08-31,Saturday,7,Sa,5,75,1,24,0,0,0,0,0,0,0,NaN